export {default as Contact} from './Contact/Contact'
export { default as Education} from './Education/Education'
export { default as Header} from './Header/Header'
export { default as HonorAndAwards} from './HonorsAndAwards/HonorsAndAwards'
export { default as Interests} from './Interests/Interests'
export { default as Languages} from './Languages/Languages'
export { default as OtherSkills} from './OtherSkills/OtherSkills'
export { default as Photo} from './Photo/Photo'
export { default as TechSkills} from './TechSkills/TechSkills'
export { default as VolunteerExperience } from './VolunteerExperience/VolunteerExperience'
export { default as WorkExperience} from './WorkExperience/WorkExperience'
export { default as LifeHistory} from './LifeHistory/LifeHistory'