import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import LandingPage from '../modules/LandingPage/LandingPage'
import "typeface-cormorant";

const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>J. Alejandro Coronado | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </div>
  )
}

export default Home